/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import utils.Console;

import static org.junit.Assert.*;

public class AppTest {

    @Test
    public void testJavaWine() {
        coding.java.Wine.displayLocalTestWines();
        coding.java.Wine.findAllById(coding.java.Wine.testIds).thenApply(wines -> Console.log(wines));
    }

    // @Test
    // public void testJavaSlangWine() {
    //     coding.javaslang.Wine.displayLocalTestWines();
    //     coding.javaslang.Wine.findAllById(coding.javaslang.Wine.testIds).map(wines -> Console.log(wines.mkString("\n")));
    // }
}
